use_frameworks!
platform :ios, '10.3'

target 'RTBackendTalk_Example' do
  pod 'RTBackendTalk', :path => '../'
  pod 'SwiftLint'

  target 'RTBackendTalk_Tests' do
    inherit! :search_paths

    
  end
end
